### ISSUE TITLE
NoMethodError: undefined method `chat' for nil:NilClass

### ISSUE THREAD

**Issue by yegor256** [yegor256/telepost#3]
```
NoMethodError: undefined method `chat' for nil:NilClass
  from telepost.rb:75:in `block in run'
  from telebot/bot.rb:32:in `process_update'
  from telebot/bot.rb:23:in `block (2 levels) in run'
  from telebot/bot.rb:21:in `each'
  from telebot/bot.rb:21:in `block in run'
  from telebot/bot.rb:15:in `loop'
  from telebot/bot.rb:15:in `run'
  from telepost.rb:70:in `run'
  from wts.rb:162:in `block (2 levels) in <top (required)>'
```

**Comment by yegor256** [comment]
@rultor release, tag is `0.2.1`
