### ISSUE TITLE
NameError: undefined local variable or method `msg'

### ISSUE THREAD

**Issue by yegor256** [yegor256/telepost#4]
```
NameError: undefined local variable or method `msg' for #<Telepost:0x00007f2e04004130>
  from telepost.rb:98:in `rescue in post'
  from telepost.rb:90:in `post'
  from telepost.rb:76:in `block in run'
  from telebot/bot.rb:32:in `process_update'
  from telebot/bot.rb:23:in `block (2 levels) in run'
  from telebot/bot.rb:21:in `each'
  from telebot/bot.rb:21:in `block in run'
  from telebot/bot.rb:15:in `loop'
  from telebot/bot.rb:15:in `run'
  from telepost.rb:72:in `run'
  from wts.rb:161:in `block (2 levels) in <top (required)>'
```

**Comment by yegor256** [comment]
@rultor release tag is `0.2.2`
