### ISSUE TITLE
Net::OpenTimeout: Net::OpenTimeout

### ISSUE THREAD

**Issue by yegor256** [yegor256/telepost#5]
```
Net::OpenTimeout: Net::OpenTimeout
  from net/protocol.rb:41:in `ssl_socket_connect'
  from net/http.rb:981:in `connect'
  from net/http.rb:920:in `do_start'
  from net/http.rb:909:in `start'
  from net/http.rb:1455:in `request'
  from faraday/adapter/net_http.rb:87:in `perform_request'
  from faraday/adapter/net_http.rb:43:in `block in call'
  from faraday/adapter/net_http.rb:92:in `with_net_http_connection'
  from faraday/adapter/net_http.rb:38:in `call'
  from faraday_middleware/response_middleware.rb:31:in `call'
  from faraday/request/url_encoded.rb:15:in `call'
  from faraday/request/multipart.rb:15:in `call'
  from faraday/rack_builder.rb:143:in `build_response'
  from faraday/connection.rb:387:in `run_request'
  from faraday/connection.rb:175:in `post'
  from telebot/client.rb:219:in `call'
  from telebot/client.rb:51:in `get_updates'
  from telebot/bot.rb:19:in `block in run'
  from telebot/bot.rb:15:in `loop'
  from telebot/bot.rb:15:in `run'
  from telepost.rb:72:in `run'
```

**Comment by yegor256** [comment]
@rultor release, tag is `0.2.3`

**Comment by yegor256** [comment]
@rultor release, tag is `0.2.3`
